# -*- coding: utf-8 -*-
"""Quine-Mccluskey Coding Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18DXW9XXYV90psuddCwR9xN06T3bdTrsA
"""

## QUINE-MCCLUSKEY CODING ASSIGNMENT

## LIBLARIES IMPORTED



## INPUTS FOR VARIABLES AND MINTERMS

def Var_In():

    global var
    var = input("How many variables would you like to use? ")


    try:
        var = int(var)
        if (0 < var <= 26) is False:
            raise ValueError("Value set should be a positive integer from 1 to 26.")

    except ValueError:
        raise ValueError("Value set should be a positive integer from 1 to 26.")


    global LL                  ## Lower Limit.
    LL = 0

    global UL                  ## Upper Limit.
    UL = (var ** 2) - 1        ## Getting the square of the variable value and subtracting 1 gives the
                               ## upper limit, max minterm.

    print("Minterms is from " + str(LL) + " to " + str(UL) + ".")

    mint = input("What are the minterms: ")
    SOP = [int(term) for term in mint.strip().split()]    ## converts the elements of the the list into integers.

    return var, LL, UL, SOP


var, LL, UL, SOP = Var_In()

print(f"Number of variables: {var}")
print(f"Minterm range: {LL} to {UL}")
print(f"Entered minterms nigga: {SOP}")